name: Build Flutter APKs and IPA files

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '17'

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Universal APK
        run: flutter build apk --release

      - name: Build Split APKs
        run: flutter build apk --release --split-per-abi

      - name: Build IPA
        continue-on-error: true
        run: flutter build ipa --release --no-codesign

      - name: Upload Universal APK
        uses: actions/upload-artifact@v4
        with:
          name: universal-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Split APKs
        uses: actions/upload-artifact@v4
        with:
          name: split-apks
          path: build/app/outputs/flutter-apk/*.apk

      - name: Upload IPA
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
          if-no-files-found: ignore
